[package]
name = "tower-cookies"
version = "0.1.1"
edition = "2018"
description = "A tower (axum) cookies manager"
keywords = ["tower", "axum"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/imbolc/tower-cookies"

[features]
default = ["axum", "tower-layer"]

[dependencies]
axum = { version = "0.2", optional = true }
cookie = { version = "0.15", features = ["percent-encode"] }
futures-util = "0.3"
http = "0.2"
parking_lot = "0.11"
pin-project-lite = "0.2"
tower-layer = { version = "0.3", optional = true }
tower-service = "0.3"

[dev-dependencies]
hyper = "0.14"
rusty-hook = "0.11"
tokio = { version = "1", features = ["full"] }
tower = "0.4"
tracing-subscriber = "0.2"
